In [1]:
import numpy as np 

In [21]:
import pandas as pd

In [29]:
 !pip install numpy

In [6]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [7]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  7.3

# Creating Arrays 

In [10]:
sample_array =  np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [11]:
sample_array.dtype

dtype('int64')

In [12]:
# Signature: np.ones(shape, dtype=None, order='C')
# Docstring:
# Return a new array of given shape and type, filled with ones.

ones = np.ones((2, 3))

In [13]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
type(ones)

numpy.ndarray

In [16]:
# Docstring:
# zeros(shape, dtype=float, order='C')

# Return a new array of given shape and type, filled with zeros.

zeros = np.zeros((2, 3))

In [17]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Docstring:
# arange([start,] stop[, step,], dtype=None)

# Return evenly spaced values within a given interval.

range_array = np.arange(0, 10 ,2)

In [19]:
range_array

array([0, 2, 4, 6, 8])

In [33]:
# Docstring:
# randint(low, high=None, size=None, dtype='l')

# Return random integers from `low` (inclusive) to `high` (exclusive).

random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 1, 8, 7, 8],
       [1, 7, 1, 9, 4],
       [4, 4, 0, 0, 0]])

In [34]:
random_array.shape

(3, 5)

In [35]:
random_array.size

15

In [41]:
np.random.random((5, 3))

array([[0.60942238, 0.17489154, 0.31517225],
       [0.74875495, 0.85204265, 0.46308806],
       [0.18966893, 0.83934884, 0.75795599],
       [0.69200756, 0.68735703, 0.93843085],
       [0.64369299, 0.48331467, 0.10372846]])

In [ ]:
randow_array_2 = np.random.random((5, 3))