In [1]:
import numpy as np 

In [21]:
import pandas as pd

In [29]:
 !pip install numpy

In [6]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [7]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  7.3

# Creating Arrays 

In [10]:
sample_array =  np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [11]:
sample_array.dtype

dtype('int64')

In [12]:
# Signature: np.ones(shape, dtype=None, order='C')
# Docstring:
# Return a new array of given shape and type, filled with ones.

ones = np.ones((2, 3))

In [13]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
type(ones)

numpy.ndarray

In [16]:
# Docstring:
# zeros(shape, dtype=float, order='C')

# Return a new array of given shape and type, filled with zeros.

zeros = np.zeros((2, 3))

In [17]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Docstring:
# arange([start,] stop[, step,], dtype=None)

# Return evenly spaced values within a given interval.

range_array = np.arange(0, 10 ,2)

In [19]:
range_array

array([0, 2, 4, 6, 8])

In [33]:
# Docstring:
# randint(low, high=None, size=None, dtype='l')

# Return random integers from `low` (inclusive) to `high` (exclusive).

random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 1, 8, 7, 8],
       [1, 7, 1, 9, 4],
       [4, 4, 0, 0, 0]])

In [34]:
random_array.shape

(3, 5)

In [35]:
random_array.size

15

In [41]:
# Docstring:
# random(size=None)

# Return random floats in the half-open interval [0.0, 1.0). Alias for

np.random.random((5, 3))

array([[0.60942238, 0.17489154, 0.31517225],
       [0.74875495, 0.85204265, 0.46308806],
       [0.18966893, 0.83934884, 0.75795599],
       [0.69200756, 0.68735703, 0.93843085],
       [0.64369299, 0.48331467, 0.10372846]])

In [42]:
randow_array_2 = np.random.random((5, 3))
randow_array_2

array([[0.38941001, 0.26228433, 0.1104131 ],
       [0.86251109, 0.32258309, 0.68482968],
       [0.05269058, 0.83272764, 0.22238133],
       [0.81505331, 0.6852715 , 0.43911768],
       [0.99542058, 0.42975551, 0.69103533]])

In [43]:
randow_array_2.shape

(5, 3)

In [44]:
randow_array_3 = np.random.random((12, 8))
randow_array_3

array([[0.71387959, 0.12601441, 0.92008202, 0.33984357, 0.7449178 ,
        0.85729552, 0.62155699, 0.49955557],
       [0.08677538, 0.71897912, 0.20457052, 0.29257797, 0.54016844,
        0.79631281, 0.26799558, 0.31086252],
       [0.51721042, 0.04220995, 0.49837481, 0.8492839 , 0.71083356,
        0.13036568, 0.25573123, 0.56067834],
       [0.37731908, 0.14490595, 0.42663208, 0.82395911, 0.99735085,
        0.89360255, 0.69259577, 0.28833713],
       [0.56346825, 0.92234557, 0.84385688, 0.8460382 , 0.85008856,
        0.30080704, 0.92331608, 0.00329719],
       [0.28718491, 0.44149339, 0.72765235, 0.64710219, 0.6358665 ,
        0.60686287, 0.25201291, 0.43277389],
       [0.15292278, 0.36377211, 0.85538501, 0.55950252, 0.20025535,
        0.24232342, 0.55370051, 0.06494957],
       [0.67593139, 0.26464158, 0.94116885, 0.98157178, 0.69386252,
        0.84787235, 0.82123778, 0.64778547],
       [0.0256863 , 0.17559954, 0.62716528, 0.16992837, 0.96098872,
        0.39673864, 0.590521