In [1]:
import numpy as np 

# Data Types & Attributes

In [26]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [24]:
# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]]a1)

In [22]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 7.3]])

In [21]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
type(a2)

numpy.ndarray

In [28]:
type(a3)

numpy.ndarray

In [29]:
a1.shape

(3,)

In [30]:
a2.shape

(2, 3)

In [31]:
a3.shape

(3, 3)

In [33]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

In [34]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [35]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [36]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [52]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [48]:
# Create a dataframe from a numpy array

df = pd.DataFrame(a2)
df

NameError: name 'pd' is not defined