In [1]:
import numpy as np 

In [2]:
import pandas as pd

In [4]:
# Pseudo-random numbers
# Docstring:
# seed(self, seed=None)

# Reseed a legacy MT19937 BitGenerator
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [17]:
random_array_4

array([[5, 8, 5],
       [7, 8, 6],
       [6, 1, 8],
       [5, 1, 8],
       [9, 1, 7]])

In [16]:
random_array_4.shape

(5, 3)

In [7]:
random_array_4.size

15

In [9]:
np.random.seed(seed=65)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 8, 5],
       [7, 8, 6],
       [6, 1, 8],
       [5, 1, 8],
       [9, 1, 7]])

In [13]:
np.random.seed(seed=98)

random_array_5 = np.random.random((10, 12))
random_array_5

array([[0.73226725, 0.56718902, 0.30122389, 0.78058293, 0.49787428,
        0.11891019, 0.38855952, 0.39464279, 0.33752558, 0.08255076,
        0.36519776, 0.4088914 ],
       [0.93326466, 0.29199227, 0.83864138, 0.989218  , 0.41527419,
        0.69708943, 0.95992938, 0.43898661, 0.6864842 , 0.29715185,
        0.97792204, 0.69332166],
       [0.03178681, 0.13107755, 0.26430383, 0.88691402, 0.85834939,
        0.65024762, 0.81720146, 0.54844453, 0.52098142, 0.60294185,
        0.17634565, 0.96960967],
       [0.16708255, 0.4692575 , 0.52043678, 0.80048465, 0.98472257,
        0.71800684, 0.42599286, 0.06659858, 0.07810161, 0.01768482,
        0.4384927 , 0.16558046],
       [0.2030054 , 0.00542521, 0.83638178, 0.60786039, 0.49074426,
        0.33302583, 0.72835933, 0.03373803, 0.27920709, 0.19088044,
        0.09430506, 0.35981857],
       [0.25519482, 0.03714533, 0.20586749, 0.35608851, 0.48879445,
        0.37132357, 0.66266775, 0.4516587 , 0.43550841, 0.29761139,
        0.32790396,

In [14]:
random_array_5 = np.random.random((10, 12))
random_array_5

array([[0.3704689 , 0.58371669, 0.50499737, 0.69416352, 0.78055249,
        0.23983481, 0.99395091, 0.77742871, 0.54721533, 0.99057706,
        0.93683767, 0.72999862],
       [0.68113481, 0.26071119, 0.69458699, 0.43151026, 0.36260885,
        0.67142119, 0.73974565, 0.62540214, 0.38280389, 0.3960137 ,
        0.86890269, 0.66923465],
       [0.44227974, 0.85847753, 0.3904516 , 0.61011742, 0.4253389 ,
        0.16496279, 0.32356441, 0.46804484, 0.75530748, 0.7259055 ,
        0.49647352, 0.37313883],
       [0.83079057, 0.08089886, 0.31457938, 0.07259025, 0.54847623,
        0.56797516, 0.9180271 , 0.61629215, 0.23358107, 0.22073619,
        0.97277144, 0.10167787],
       [0.26908216, 0.55246084, 0.15060211, 0.38480153, 0.17960831,
        0.43081263, 0.07443633, 0.37574405, 0.69147035, 0.75684334,
        0.90973592, 0.08582452],
       [0.42604129, 0.16296828, 0.02430796, 0.41783743, 0.48081183,
        0.54560742, 0.10535933, 0.03730877, 0.1002763 , 0.12134276,
        0.16674749,