In [1]:
import numpy as np 
import pandas as pd

In [2]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[6, 6, 3, 5, 5],
       [7, 8, 5, 3, 9],
       [6, 0, 8, 5, 4]])

In [3]:
random_array.shape

(3, 5)

In [4]:
np.sort(random_array)

array([[3, 5, 5, 6, 6],
       [3, 5, 7, 8, 9],
       [0, 4, 5, 6, 8]])

In [7]:
random_array

array([[6, 6, 3, 5, 5],
       [7, 8, 5, 3, 9],
       [6, 0, 8, 5, 4]])

In [6]:
np.argsort(random_array)

array([[2, 3, 4, 0, 1],
       [3, 2, 0, 1, 4],
       [1, 4, 3, 0, 2]])

In [9]:
np.argmax(random_array)

9

In [10]:
np.argmax(random_array, axis=0)

array([1, 1, 2, 0, 1])

In [11]:
np.argmax(random_array, axis=1)

array([0, 4, 2])