# Manipulating & comparing arrays

# Arithmetic 

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [3]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [4]:
a1

array([1, 2, 3])

In [12]:
ones = np.ones(3)

In [13]:
ones

array([1., 1., 1.])

In [14]:
a1 + ones

array([2., 3., 4.])

In [9]:
a1 - ones

array([0., 1., 2.])

In [10]:
a1*ones

array([1., 2., 3.])

In [15]:
a1/ones

array([1., 2., 3.])

In [12]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 7.3]])

In [13]:
a1*a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10. , 21.9]])

In [14]:
a1+a1

array([2, 4, 6])

In [15]:
a1+a2

array([[ 2. ,  4. ,  6.4],
       [ 5. ,  7. , 10.3]])

In [17]:
a1 + a2 * a1 * a2 / a2 - a1 - a2 * a2

array([[  0.  ,   0.  ,  -1.36],
       [-12.  , -15.  , -31.39]])

In [18]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Floor division removes the decimals (rounds down )
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [5]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 7.3]])

In [6]:
a1 ** 2

array([1, 4, 9])

In [7]:
3.3 * 3.3

10.889999999999999

In [8]:
np.square(a2)

array([[ 1.  ,  4.  , 11.56],
       [16.  , 25.  , 53.29]])

In [16]:
# Call signature:  np.add(*args, **kwargs)
# Type:            ufunc
# String form:     <ufunc 'add'>

np.add(a1, ones)

array([2., 3., 4.])

In [18]:
a1 % 2

array([1, 0, 1])

In [19]:
a1 / 2

array([0.5, 1. , 1.5])

In [20]:
a2 % 2

array([[1. , 0. , 1.4],
       [0. , 1. , 1.3]])

In [21]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [22]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])