# Manipulating & comparing arrays

# Arithmetic 

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [3]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [4]:
a1

array([1, 2, 3])

In [6]:
ones = np.ones(3)

In [7]:
ones

array([1., 1., 1.])

In [8]:
a1 + ones

array([2., 3., 4.])

In [9]:
a1 - ones

array([0., 1., 2.])

In [10]:
a1*ones

array([1., 2., 3.])

In [11]:
a1/ones

array([1., 2., 3.])

In [12]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 7.3]])

In [13]:
a1*a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10. , 21.9]])

In [14]:
a1+a1

array([2, 4, 6])

In [15]:
a1+a2

array([[ 2. ,  4. ,  6.4],
       [ 5. ,  7. , 10.3]])

In [17]:
a1 + a2 * a1 * a2 / a2 - a1 - a2 * a2

array([[  0.  ,   0.  ,  -1.36],
       [-12.  , -15.  , -31.39]])

In [18]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a1 + a2 + a3 * a1 * a2 * a3

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 