# Viewing Arrays and Matrices

In [1]:
import numpy as np 

In [2]:
import pandas as pd

In [4]:
# Signature:
# np.unique(
#    ar,
#    return_index=False,
    
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [5]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [6]:
np.unique (random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [9]:
# Type:            ndarray
# String form:     [1 2 3]
# Length:          3

a1[0]

1

In [10]:
a2[0]

array([1. , 2. , 3.4])

In [11]:
a3[0]

array([1, 2, 3])

In [12]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 7.3]])

In [15]:
a2[1]

array([4. , 5. , 7.3])

In [20]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a3.shape

(3, 3)

In [22]:
a3[:1, :1]

array([[1]])

In [23]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [24]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [25]:
# Get the first 4 number of the inner most arrays 
a4[:, :, :, :1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])