# Viewing Arrays and Matrices

In [1]:
import numpy as np 

In [2]:
import pandas as pd

In [4]:
# Signature:
# np.unique(
#    ar,
#    return_index=False,
    
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [5]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [6]:
np.unique (random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Numpy's ain datatype is ndarray
# Name : Array , Vector
# 1 Dimensional
# Shape = (1,3)

a1 = np.array([1, 2, 3])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3)

a2 = np.array([[1, 2.0, 3.4],[4, 5, 7.3]])

# Name : Array , Matrix
# More than 1 Dimensional
# Shape = (2,3,3) { Axis = 0 (2), Axis = 1 (3), Axis = n (3)}

a3 = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]])

In [9]:
# Type:            ndarray
# String form:     [1 2 3]
# Length:          3

a1[0]

1

In [10]:
a2[0]

array([1. , 2. , 3.4])

In [11]:
a3[0]

array([1, 2, 3])

In [12]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])