# Datatypes & Attributes

In [1]:
import numpy as np

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[12, 23, 3.4],
             [17, 45, 5.3]])

a3 = np.array([[[16, 45, 23],
               [45, 23, 64],
               [67, 45, 65]],
              [[43, 84, 29],
              [67, 49, 24],
              [98, 59, 87]]])

In [7]:
a2

array([[12. , 23. ,  3.4],
       [17. , 45. ,  5.3]])

In [8]:
a3

array([[[16, 45, 23],
        [45, 23, 64],
        [67, 45, 65]],

       [[43, 84, 29],
        [67, 49, 24],
        [98, 59, 87]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)